### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by Kolionixee** [Fergs32/DotDoxOfficial#1]
Hi, I have a problem because when I try to fire this file, nothing happens, do I have to download something or something? if so please reply

**Comment by Fergs32** [comment]
Hi, I just did a small update to the program which might help with it not launching. If you're downloading the code in the raw format, you'll need to load it up using visual studio 2019 or 2022, not 2021. If you're downloading the "exe" folder, which contains the files to launch the program it should work.

Your exe folder should look something like this
![Screenshot 2023-06-28 164304](https://github.com/Fergs32/DotDoxOfficial/assets/93891128/e46830c5-cd31-47d8-b0b7-214eb5fecc2b)

If your PC is not in standard US/GB format then there might be some OS communication problems when translation occurs. 

If possible, drag your program into the CMD and hit enter, if an error occurs it will display that, and send me the screenshot

**Comment by Kolionixee** [comment]
https://github.com/Fergs32/DotDoxOfficial/assets/134411836/f0409a66-79e2-439a-8078-00dc11ca14fa

**Comment by Kolionixee** [comment]
when i opened it via cmd it said i need to download .net i downloaded it but it doesn't work

**Comment by Kolionixee** [comment]
https://www.mediafire.com/file/g8b01ciuw1uib2w/bandicam_2023-06-29_20-03-55-342.mp4/file

**Comment by Kolionixee** [comment]
half things are not working well
