### ISSUE TITLE
framework problem

### ISSUE THREAD

**Issue by gittrippinbro** [Fergs32/DotDoxOfficial#3]
First, I ran the exe. Then a window popped up then disappeared.
Then I ran the exe in the command prompt. this happened.
<img width="1329" alt="Screenshot 2023-11-05 at 12 18 02 PM" src="https://github.com/Fergs32/DotDoxOfficial/assets/149457656/f6df1b60-6f1b-46d9-820c-11c8645796e9">

**Comment by Fergs32** [comment]
Install the framework that is linked below "To install missing framework, download" and download desktop applications framework

**Comment by gittrippinbro** [comment]
thx
